# Generated by Django 5.0.14 on 2025-11-02 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetitem",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Link this budget item to a vendor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_items",
                to="vendors.eventvendor",
            ),
        ),
    ]
